# Generated by Django 2.1.4 on 2018-12-26 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('observaciones', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('observaciones', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=100)),
                ('precio', models.FloatField(default=0)),
                ('unidades', models.CharField(max_length=20)),
                ('observaciones', models.TextField(max_length=500)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platosapp.Familia')),
            ],
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='plato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platosapp.Plato'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platosapp.Producto'),
        ),
    ]
