# Generated by Django 2.1.4 on 2018-12-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platosapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='observaciones',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='observaciones',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='observaciones',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
