# Generated by Django 2.1.4 on 2018-12-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platosapp', '0002_auto_20181226_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='observaciones',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='plato',
            name='observaciones',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='observaciones',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
