# Generated by Django 2.1.4 on 2018-12-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platosapp', '0003_auto_20181226_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='categoria',
            field=models.CharField(default='', max_length=100),
        ),
    ]
