# Generated by Django 2.2.10 on 2020-03-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platosapp', '0005_auto_20181226_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='precio_venta',
            field=models.FloatField(default=0),
        ),
    ]
